<html>

<?php include "../inc/dbinfo.inc"; ?>

<?php

  /* Connect to MySQL and select the database. */
  $connection = mysqli_connect(DB_SERVER, DB_USERNAME, DB_PASSWORD);

  if (mysqli_connect_errno()) echo "Failed to connect to MySQL: " . mysqli_connect_error();

  $database = mysqli_select_db($connection, DB_DATABASE);
?>


<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script type="text/javascript">


	
		var type = []; 
		type["GSD"] = [

 "Buster Sword I",
 "Buster Sword II",
 "Buster Sword III",
 "Buster Blade I",
 "Buster Blade II",
 "Buster Blade III",
 "Chrome Razor I",
 "Chrome Razor II",
 "Nergal Judicator",
 "Purgations Atrocity",
 "Thunder Blade I",
 "Thunder Blade II",
 "Lightning Punisher I",
 "Lightning Punisher II",
 "Lightning Punisher III",
 "Freeze Blade I",
 "Freeze Blade II",
 "Freeze Blade III",
 "Frost Blade I",
 "Frost Blade II",
 "Jagras Blade I",
 "Jagras Blade II",
 "Jagras Blade III",
 "Jagras Hacker I",
 "Jagras Hacker II",
 "Jagras Hacker III",
 "Girros Blade I",
 "Girros Blade II",
 "Maladys Kiss I",
 "Maladys Kiss II",
 "Maladys Kiss III",
 "Lava Blaze I",
 "Lava Blaze II",
 "Lava Blaze III",
 "Blooming Blade I",
 "Blooming Blade II",
 "Blooming Blade III",
 "Datura Blaze I",
 "Datura Blaze II",
 "Datura Blaze III",
 "Flame Blade I",
 "Flame Blade II",
 "Red Wing",
 "Blue Wing",
 "Rathalos Glinsword",
 "Bone Blade I",
 "Bone Blade II",
 "Bone Blade III",
 "Bone Slasher I",
 "Bone Slasher II",
 "Bone Slasher III",
 "Giant Jawblade I",
 "Giant Jawblade II",
 "Hazak Kys",
 "Leviathans Fury",
 "Flammenzahn",
 "Flammenzahn+",
 "Gnashing Flammenzahn+",
 "Aqua Slasher I",
 "Aqua Slasher II",
 "Aqua Slasher III",
 "Water Golem I",
 "Water Golem II",
 "Water Golem III",
 "Carapace Buster I",
 "Carapace Buster II",
 "Carapace Buster III",
 "Barroth Shredder I",
 "Barroth Shredder II",
 "Barroth Shredder III",
 "Spiked Blade I",
 "Spiked Blade II",
 "Radobaan Slab I",
 "Radobaan Slab II",
 "Radobaan Slab III",
 "Dragonbone Cleaver I",
 "Dragonbone Cleaver II",
 "Dragonbone Cleaver III",
 "Thundersword",
 "Kirin Thundersword",
 "King Thundersword",
 "Magda Potestas I",
 "Magda Potestas II",
 "Blacksteel Chopper I",
 "Blacksteel Chopper II",
 "Icesteel Edge ",
 "Daoras Decimator",
 "Xeno Maliq",
 "Wyvern Jawblade",
 "Great Wyvern Jawblade",
 "Berserker Sword",
 "Anguish" 
	];

	type["LSD"] = [
"Iron Katana I",
 "Iron Katana II",
 "Iron Katana III",
 "Iron Grace I",
 "Iron Grace II",
 "Iron Grace III",
 "Iron Gospel I",
 "Iron Gospel II",
 "Nergal Reaver",
 "Exterminations Edge",
 "Flickering Glow I",
 "Flickering Glow II",
 "Dazzling Flash I",
 "Dazzling Flash II",
 "Dazzling Flash III",
 "First Dance I",
 "First Dance II",
 "First Dance III",
 "Last Dance I",
 "Last Dance II",
 "Last Dance III",
 "Brazen Ridge I",
 "Brazen Ridge II",
 "Wyvernblade “Leaf”",
 "Wyvernblade “Verde”",
 "Wyvernblade “Holly”",
 "Wyvernblade “Fall”",
 "Wyvernblade “Blood”",
 "Wyvernblade “Azure”",
 "Wyvernblade “Indigo”",
 "Bone Shotel I",
 "Bone Shotel II",
 "Bone Shotel III",
 "Hard Bone Shotel I",
 "Hard Bone Shotel II",
 "Hard Bone Shotel III",
 "Bone Reaper I",
 "Bone Reaper II",
 "Rookslayer Long Sword",
 "Bazel Varga Rookslayer",
 "Blazing Shotel I",
 "Blazing Shotel II",
 "Anja Scimitar I",
 "Anja Scimitar II",
 "Anja Scimitar III",
 "Jyura Shotel I",
 "Jyura Shotel II",
 "Jyura Shotel III",
 "Dipterus I",
 "Dipterus II",
 "Dipterus III",
 "Hazak Grosser I",
 "Hazak Grosser II",
 "Pulsar Shotel I",
 "Pulsar Shotel II",
 "Pulsar Shotel III",
 "Kadachi Fang I",
 "Kadachi Fang II",
 "Kadachi Fang III",
 "Glacial Shotel I",
 "Glacial Shotel II",
 "Stealer",
 "Legia Stealer",
 "Dark Shotel I",
 "Dark Shotel II",
 "Dark Scimitar I",
 "Dark Scimitar II",
 "Dark Scimitar III",
 "Dragonbone Stabber I",
 "Dragonbone Stabber II",
 "Dragonbone Stabber III",
 "Magda Facultas I",
 "Magda Facultas II",
 "Blacksteel Long Sword I",
 "Blacksteel Long Sword II",
 "Imperial Saber",
 "Imperial Shimmer",
 "Xeno Cypher",
 "Supremacy Blade",
 "Divine Slasher",
 "Reaver Cruelty",
 "Reaver Calamity",
 
];

	type["HAM"] = [
"Iron Hammer I",
 "Iron Hammer II",
 "Iron Hammer III",
 "Iron Demon I",
 "Iron Demon II",
 "Iron Demon III",
 "Iron Archdemon I",
 "Iron Archdemon II",
 "Nergal Crusher",
 "Obliterations Footfall",
 "Frozen Core",
 "Frozen Core+",
 "Cocytus",
 "Aqua Hammer I",
 "Aqua Hammer II",
 "Aqua Hammer III",
 "Water Basher I",
 "Water Basher II",
 "Water Basher III",
 "Girros Hammer I",
 "Girros Hammer II",
 "Maladys Fist I",
 "Maladys Fist II",
 "Maladys Fist III",
 "Blooming Hammer I",
 "Blooming Hammer II",
 "Blooming Hammer III",
 "Buon Fiore",
 "Thunder Hammer I",
 "Thunder Hammer II",
 "Lightning Bash I",
 "Lightning Bash II",
 "Lightning Bash III",
 "Bone Bludgeon I",
 "Bone Bludgeon II",
 "Bone Bludgeon III",
 "Fossil Bludgeon I",
 "Fossil Bludgeon II",
 "Fossil Bludgeon III",
 "Grandrock I",
 "Grandrock II",
 "Hazak Vlafos",
 "Pandemoniums Root",
 "Bone Spike I",
 "Bone Spike II",
 "Baan Strike I",
 "Baan Strike II",
 "Baan Strike III",
 "Brazenbreak I",
 "Brazenbreak II",
 "Kulu Beak I",
 "Kulu Beak II",
 "Kulu Beak III",
 "Crushing Beak I",
 "Crushing Beak II",
 "Crushing Beak III",
 "Diablos Sledge I",
 "Diablos Sledge II",
 "Diablos Shatterer I",
 "Diablos Shatterer II",
 "Carapace Sledge I",
 "Carapace Sledge II",
 "Carapace Sledge III",
 "Barroth Breaker I",
 "Barroth Breaker II",
 "Barroth Breaker III",
 "Blazing Hammer I",
 "Blazing Hammer II",
 "Anja Striker I",
 "Anja Striker II",
 "Anja Striker III",
 "Dragonbone Basher I",
 "Dragonbone Bashet II",
 "Dragonbone Bashet III",
 "Magda Floga",
 "Ragefire Magda Floga",
 "Blacksteel Hammer I",
 "Blacksteel Hammer II",
 "Icesteel Hammer",
 "Daoras Colossus",
 "Xeno Maph Agarna",
 "Jail Hammer",
 "Binder Mace",
 "Devils Due",
 "Devils Crush"
];

	type["HTH"] = [
"Metal Bagpipe I",
 "Metal Bagpipe II",
 "Metal Bagpipe III",
 "Great Bagpipe I",
 "Great Bagpipe II",
 "Great Bagpipe III",
 "Fortissimo I",
 "Fortissimo II",
 "Nergal Groove",
 "Desolations Overture",
 "Thunder Gaida I",
 "Thunder Gaida II",
 "Lightning Drmu I",
 "Lightning Drmu II",
 "Lightning Drmu III",
 "Kula Duda I",
 "Kula Duda II",
 "Kula Duda III",
 "Dancing Duval I",
 "Dancing Duval II",
 "Dancing Duval III",
 "Valkyrie Chordmaker",
 "Queen Chordmaker",
 "Coral Chordmaker",
 "Royal Chordmaker",
 "Aqua Bagpipe I",
 "Aqua Bagpipe II",
 "Aqua Bagpipe III",
 "Water Tamtam I",
 "Water Tamtam II",
 "Water Tamtam III",
 "Glacial Bagpipe I",
 "Glacial Bagpipe II",
 "Glacial Bagpipe III",
 "Sectored",
 "Legia Sectored",
 "Bone Horn I",
 "Bone Horn II",
 "Bone Horn III",
 "Hard Bone Horn I",
 "Hard Bone Horn II",
 "Hard Bone Horn II",
 "Heavy Bone Horn I",
 "Heavy Bone Horn II",
 "Gama Horn I",
 "Gama Horn II",
 "Blazing Horn I",
 "Blazing Horn II",
 "Anja Barone I",
 "Anja Barone II",
 "Anja Barone III",
 "Blooming Horn I",
 "Blooming Horn II",
 "Blooming Horn III",
 "Datura Horn I",
 "Datura Horn II",
 "Datura Horn III",
 "Luma Horn I",
 "Luma Horn II",
 "Luma Barone I",
 "Luma Barone II",
 "Luma Barone III",
 "Rookslayer Drum",
 "Bazelreid Rookslayer",
 "Sonic Horn I",
 "Sonic Horn II",
 "Sonic Horn III",
 "Glass Royale",
 "Glass Royale+",
 "Queen Vespoid Horn",
 "Spiked Horn I",
 "Spiked Horn II",
 "Baan Horn I",
 "Baan Horn II",
 "Baan Horn III",
 "Dragonbone Auldhorn I",
 "Dragonbone Auldhorn II",
 "Dragonbone Auldhorn III",
 "Thundercry Horn",
 "Thunderbolt Horn I",
 "Thunderbolt Horn II",
 "Blacksteel Dragonhorn I",
 "Blacksteel Dragonhorn II",
 "Teostras Tiple",
 "Teostras Orphee",
 "Xeno Mamasheena",
 "Devils Maestro",
 "Vero"
];

	type["DBL"] = [
 "Matched Slicers I",
 "Matched Slicers II",
 "Matched Slicers III",
 "Dual Slicers I",
 "Dual Slicers II",
 "Dual Slicers III",
 "Chrome Slicers I",
 "Chrome Slicers II",
 "Nergal Gouge",
 "Decimation Claws",
 "Luminous Daggers I",
 "Luminous Daggers II",
 "Dual Destroyers I",
 "Dual Destroyers II",
 "Dual Destroyers III",
 "Rookslayer Handaxes",
 "Bazelhawk Rookslayer",
 "Freeze Daggers I",
 "Freeze Daggers II",
 "Freeze Chain I",
 "Freeze Chain II",
 "Rending Beaks I",
 "Rending Beaks II",
 "Rending Beaks III",
 "Arcanaria I",
 "Arcanaria II",
 "Arcanaria III",
 "Sworn Rapiers",
 "Sworn Rapiers+",
 "Holy Sabers",
 "Bone Hatchets I",
 "Bone Hatchets II",
 "Bone Hatchets III",
 "Wild Hatchets I",
 "Wild Hatchets II",
 "Wild Hatchets III",
 "Strong Hatchets I",
 "Strong Hatchets II",
 "Blazing Hatchets I",
 "Blazing Hatchets II",
 "Anja Cyclone I",
 "Anja Cyclone II",
 "Anja Cyclone III",
 "Diablos Hatchets I",
 "Diablos Hatchets II",
 "Diablos Clubs I",
 "Diablos Clubs II",
 "Madness Pangas I",
 "Madness Pangas II",
 "Madness Pangas III",
 "Jyura Hatchets I",
 "Jyura Hatchets II",
 "Jyura Hatchets III",
 "Lava Cyclone I",
 "Lava Cyclone II",
 "Taurus Pangas I",
 "Taurus Pangas II",
 "Dark Ripper I",
 "Dark Ripper II",
 "Dark Ripper III",
 "Pulsar Hatchets I",
 "Pulsar Hatchets II",
 "Pulsar Hatchets III",
 "Kadachi Claws I",
 "Kadachi Claws II",
 "Kadachi Claws III",
 "Garon Hatchets I",
 "Garon Hatchets II",
 "Blood-Drinker Chainblade",
 "Sin",
 "Dragonbone Twinblades I",
 "Dragonbone Twinblades II",
 "Enduring Schism",
 "Kirin Bolts",
 "Kirin Bolts+",
 "Monarch",
 "Magda Ungulae I",
 "Magda Ungulae II",
 "Blacksteel Twins I",
 "Blacksteel Twins II",
 "Twin Nails",
 "Fire and Ice",
 "Xeno Raqs",
 "Wrath and Rancor",
 "Wrathful Predation"

];
	type["SAS"] = [
 "Hunters Knife I",
 "Hunters Knife II",
 "Hunters Knife III",
 "Steel Knife I",
 "Steel Knife II",
 "Steel Knife III",
 "Chrome Slicer I",
 "Chrome Slicer II",
 "Nergal Jack",
 "Eradication Vanguard",
 "Flame Knife I",
 "Flame Knife II",
 "Heat Edge",
 "Corona",
 "Heavy Bang",
 "Heavy Bang+",
 "Master Bang",
 "Aqua Messer I",
 "Aqua Messer II",
 "Aqua Messer III",
 "Rogue Wave I",
 "Rogue Wave II",
 "Rogue Wave III",
 "Glacial Grace I",
 "Glacial Grace II",
 "Rimespire",
 "Legia Rimespire",
 "Princess Rapier",
 "Queen Rapier",
 "Queen Rose",
 "Royal Rose",
 "Lumu Knife I",
 "Lumu Knife II",
 "Lumu Tabar I",
 "Lumu Tabar II",
 "Lumu Tabar III",
 "Blooming Knife I",
 "Blooming Knife II",
 "Blooming Knife III",
 "Datura Blossom I",
 "Datura Blossom II",
 "Datura Blossom III",
 "Girros Knife I",
 "Girros Knife II",
 "Maladys Tabar I",
 "Maladys Tabar II",
 "Maladys Tabar III",
 "Bone Kukri I",
 "Bone Kukri II",
 "Bone Kukri III",
 "Chief Kukri I",
 "Chief Kukri II",
 "Chief Kukri III",
 "Grand Barong I",
 "Grand Barong II",
 "Spiked Edge I",
 "Spiked Edge II",
 "Baan Claw I",
 "Baan Claw II",
 "Baan Claw III",
 "Jagras Edge I",
 "Jagras Edge II",
 "Jagras Edge III",
 "Jagras Garotte I",
 "Jagras Garotte II",
 "Jagras Garotte III",
 "Thunder Edge I",
 "Thunder Edge II",
 "Lightning Nemesis I",
 "Lightning Nemesis II",
 "Lightning Nemesis III",
 "Carapace Edge I",
 "Carapace Edge II",
 "Carapace Edge III",
 "Barroth Club I",
 "Barroth Club II",
 "Barroth Club III",
 "Blazing Edge I",
 "Blazing Edge II",
 "Flammensuchier",
 "Gnashinh Flammensuchier",
 "Dragonbone Sword I",
 "Dragonbone Sword II",
 "Dragonbone Sword III",
 "Fulminator",
 "Thunderbolt Sword",
 "Blacksteel Sword I",
 "Blacksteel Sword II",
 "Teostras Spada",
 "Teostras Emblem",
 "Xeno Mabura",
 "Fatal Jho",
 "Fatal Bite"

];

	type["LAN"] = [
"Iron Lance I",
 "Iron Lance II",
 "Iron Lance III",
 "Steel Lance I",
 "Steel Lance II",
 "Steel Lance III",
 "Chrome Lance I",
 "Chrome Lance II",
 "Nergal Impaler",
 "Perditions Hand",
 "Glacial Lance I",
 "Glacial Lance II",
 "Legiana Halberd I",
 "Legiana Halberd II",
 "Kulu Lance I",
 "Kulu Lance II",
 "Kulu Lance III",
 "Kulu Hasta I",
 "Kulu Hasta II",
 "Kulu Hasta III",
 "Gama Pilebunker I",
 "Gama Pilebunker II",
 "Thunder Lance I",
 "Thunder Lance II",
 "Lightning Spire I",
 "Lightning Spire II",
 "Lightning Spire III",
 "Blooming Lance I",
 "Blooming Lance II",
 "Blooming Lance III",
 "Datura Pike I",
 "Datura Pike II",
 "Datura Pike III",
 "Flame Lance I",
 "Flame Lance II",
 "Red Tail",
 "Blue Tail",
 "Blue Prominence",
 "Bone Lance I",
 "Bone Lance II",
 "Bone Lance III",
 "Hard Bone Lance I",
 "Hard Bone Lance II",
 "Hard Bone Lance III",
 "Heavy Bone Lance I",
 "Heavy Bone Lance II",
 "Hazak Wachter",
 "Loves Sorrow",
 "Taurus Lance I",
 "Taurus Lance II",
 "Dark Stinger I",
 "Dark Stinger II",
 "Dark Stinger III",
 "Carapace Lance I",
 "Carapace Lance II",
 "Carapace Lance III",
 "Barroth Stinger I",
 "Barroth Stinger II",
 "Barroth Stinger III",
 "Garon Lance I",
 "Garon Lance II",
 "Garon Dhara I",
 "Garon Dhara II",
 "Aqua Horn I",
 "Aqua Horn II",
 "Aqua Horn III",
 "Water Spike I",
 "Water Spike II",
 "Water Spike III",
 "Dragonbone Lance I",
 "Dragonbone Lance II",
 "Dragonbone Lance III",
 "Rookslayer Lance",
 "Bazel Myniad Rookslayer",
 "Thunderpike",
 "Thunderspear",
 "Thunderpiercer",
 "Blacksteel Lance I",
 "Blacksteel Lance II",
 "Icesteel Spear",
 "Daora's Fang",
 "Xeno Zauta",
 "Babel Spear",
 "Elder Babel Spear",
 "Grief Lance",
 "Fiendish Tower"
];

	type["GUL"] = [
"Iron Gunlance I",
 "Iron Gunlance II",
 "Iron Gunlance III",
 "Steel Gunlance I",
 "Steel Gunlance II",
 "Steel Gunlance III",
 "Chrome Gunlance I",
 "Chrome Gunlance II",
 "Nergal Ram",
 "Eradication Flame",
 "Pulsar Gunlance I",
 "Pulsar Gunlance II",
 "Pulsar Gunlance III",
 "Kadachi Striker",
 "Kadachi Striker+",
 "Mythic Kadachi Striker",
 "Rath Gunlance I",
 "Rath Gunlance II",
 "Red Rook",
 "Blue Rook",
 "Blue Chariot",
 "Princess Panoply",
 "Princess Panoply+",
 "Rose Burst",
 "Royal Burst",
 "Madness Gunlance I",
 "Madness Gunlance II",
 "Madness Gunlance III",
 "Jyura Buster I",
 "Jyura Buster II",
 "Jyura Buster III",
 "Glacial Gunlance I",
 "Glacial Gunlance II",
 "Legiana Cannon I",
 "Legiana Cannon II",
 "Bone Gunlance I",
 "Bone Gunlance II",
 "Bone Gunlance III",
 "Bone Cannon I",
 "Bone Cannon II",
 "Bone Cannon III",
 "Great Bone Gunlance I",
 "Great Bone Gunlance II",
 "Bazel Buster I",
 "Bazel Buster II",
 "Jagras Gunlance I",
 "Jagras Gunlance II",
 "Jagras Gunlance III",
 "Glutton Gunlance I",
 "Glutton Gunlance II",
 "Glutton Gunlance III",
 "Girros Gunlance I",
 "Glutton Gunlance II",
 "Deathfang Gunlance I",
 "Deathfang Gunlance II",
 "Deathfang Gunlance III",
 "Hazak Spysa I",
 "Hazak Spysa II",
 "Carpace Cannon I",
 "Carpace Cannon II",
 "Carpace Cannon III",
 "Barroth Blaster I",
 "Barroth Blaster II",
 "Barroth Blaster III",
 "Blazing Gunlance I",
 "Blazing Gunlance II",
 "Anja Cannon I",
 "Anja Cannon II",
 "Anja Cannon III",
 "Dragonbone Gunlance I",
 "Dragonbone Gunlance II",
 "Dragonbone Gunlance III",
 "Magda Lahat",
 "Earthshaker Magda Lahat",
 "Blacksteel Gunlance I",
 "Blacksteel Gunlance II",
 "Icesteel Gunlance",
 "Daoras Brigia",
 "Xeno Hemta",
 "Ravenous Gunlance",
 "Insatiable Gunlance"
];

	type["AWS"] = [
"Proto Commission Axe I",
 "Proto Commission Axe II",
 "Proto Commission Axe III",
 "Elite Commission Axe I",
 "Elite Commission Axe II",
 "Elite Commission Axe III",
 "Chrome Guardian I",
 "Chrome Guardian II",
 "Nergal Lacerator",
 "Devestations Thorns",
 "Rathsblade",
 "Axelion Blade",
 "Halberion Blade",
 "Mudslide Blade I",
 "Mudslide Blade II",
 "Mudslide Blade III",
 "Jyura Depth I",
 "Jyura Depth II",
 "Jyura Depth III",
 "Everfrost  Blade I",
 "Everfrost  Blade II",
 "Gigafrost I",
 "Gigafrost II",
 "Dear Lutemis",
 "Dear Lutemia",
 "Dear Hecatel",
 "Dear Hecatelia",
 "Bone Strongarm I",
 "Bone Strongarm II",
 "Bone Strongarm III",
 "Hard Bone Strongarm I",
 "Hard Bone Strongarm II",
 "Hard Bone Strongarm III",
 "Mighty Strongarm I",
 "Mighty Strongarm II",
 "Diablos Wall I",
 "Diablos Wall II",
 "Diablos Tyrannis I",
 "Diablos Tyrannis II",
 "Jagras Strongarm I",
 "Jagras Strongarm II",
 "Jagras Strongarm III",
 "Jagras Escudo I",
 "Jagras Escudo II",
 "Jagras Escudo III",
 "Gama Silt I",
 "Gama Silt II",
 "Girros Strongarm I",
 "Girros Strongarm II",
 "Girros Nadja I",
 "Girros Nadja II",
 "Girros Nadja III",
 "Hazak Aspida I",
 "Hazak Aspida II",
 "Pulsar Strongarm I",
 "Pulsar Strongarm II",
 "Pulsar Strongarm III",
 "Kadachi Kaina I",
 "Kadachi Kaina II",
 "Kadachi Kaina III",
 "Garon Strongarm I",
 "Garon Strongarm II",
 "Hates Undying Flame",
 "Odium",
 "Dragonbone Cutter I",
 "Dragonbone Cutter II",
 "Dragonbone Cutter III",
 "Magda Manus",
 "Avenging Magda Manus",
 "Blacksteel Charger I",
 "Blacksteel Charger II",
 "Daoras Casca",
 "Daoras Thwartoise",
 "Xeno Raatz",
 "Tyrants Charge Blade",
 "Oppressors Charge Blade"

];

	type["CHB"] = [
 "Proto Commission Axe I",
 "Proto Commission Axe II",
 "Proto Commission Axe III",
 "Elite Commission Axe I",
 "Elite Commission Axe II",
 "Elite Commission Axe III",
 "Chrome Guardian I",
 "Chrome Guardian II",
 "Nergal Lacerator",
 "Devestations Thorns",
 "Rathsblade",
 "Axelion Blade",
 "Halberion Blade",
 "Mudslide Blade I",
 "Mudslide Blade II",
 "Mudslide Blade III",
 "Jyura Depth I",
 "Jyura Depth II",
 "Jyura Depth III",
 "Everfrost  Blade I",
 "Everfrost  Blade II",
 "Gigafrost I",
 "Gigafrost II",
 "Dear Lutemis",
 "Dear Lutemia",
 "Dear Hecatel",
 "Dear Hecatelia",
 "Bone Strongarm I",
 "Bone Strongarm II",
 "Bone Strongarm III",
 "Hard Bone Strongarm I",
 "Hard Bone Strongarm II",
 "Hard Bone Strongarm III",
 "Mighty Strongarm I",
 "Mighty Strongarm II",
 "Diablos Wall I",
 "Diablos Wall II",
 "Diablos Tyrannis I",
 "Diablos Tyrannis II",
 "Jagras Strongarm I",
 "Jagras Strongarm II",
 "Jagras Strongarm III",
 "Jagras Escudo I",
 "Jagras Escudo II",
 "Jagras Escudo III",
 "Gama Silt I",
 "Gama Silt II",
 "Girros Strongarm I",
 "Girros Strongarm II",
 "Girros Nadja I",
 "Girros Nadja II",
 "Girros Nadja III",
 "Hazak Aspida I",
 "Hazak Aspida II",
 "Pulsar Strongarm I",
 "Pulsar Strongarm II",
 "Pulsar Strongarm III",
 "Kadachi Kaina I",
 "Kadachi Kaina II",
 "Kadachi Kaina III",
 "Garon Strongarm I",
 "Garon Strongarm II",
 "Hates Undying Flame",
 "Odium",
 "Dragonbone Cutter I",
 "Dragonbone Cutter II",
 "Dragonbone Cutter III",
 "Magda Manus",
 "Avenging Magda Manus",
 "Blacksteel Charger I",
 "Blacksteel Charger II",
 "Daoras Casca",
 "Daoras Thwartoise",
 "Xeno Raatz",
 "Tyrants Charge Blade",
 "Oppressors Charge Blade"
];

	type["ING"] = [
 "Iron Blade I",
 "Iron Blade II",
 "Iron Blade III",
 "Steel Blade I",
 "Steel Blade II",
 "Steel Blade III",
 "Chrome Blade I",
 "Chrome Blade II",
 "Nergal Reaper",
 "Catastrophes Lights",
 "Flame Glaive I",
 "Flame Glaive II",
 "Rathmaul",
 "Firedance Rathmaul",
 "Kulu Blade I",
 "Kulu Blade II",
 "Kulu Blade III",
 "Ya-ku Wrath I",
 "Ya-ku Wrath II",
 "Ya-ku Wrath III",
 "Luminous Blade I",
 "Luminous Blade II",
 "Destroyer Bo I",
 "Destroyer Bo II",
 "Destroyer Bo III",
 "Frost Blade I",
 "Frost Blade II",
 "Freeze Gale I",
 "Freeze Gale II",
 "Blooming Glaive I",
 "Blooming Glaive II",
 "Blooming Glaive III",
 "Datura Blade I",
 "Datura Blade II",
 "Datura Blade III",
 "Gama Cane I",
 "Gama Cane II",
 "Bone Rod I",
 "Bone Rod II",
 "Bone Rod III",
 "Hard Bone Rod I",
 "Hard Bone Rod II",
 "Hard Bone Rod III",
 "Aerial Rod I",
 "Aerial Rod II",
 "Hazak Entoma I",
 "Hazak Entoma II",
 "Flammenkaefer",
 "Flammenkaefer+",
 "Gnashing Flammenkaefer",
 "Aqua Rod I",
 "Aqua Rod II",
 "Aqua Rod III",
 "Water Glaive I",
 "Water Glaive II",
 "Water Glaive III",
 "Diablos Rod I",
 "Diablos Rod II",
 "Tyrannis Glaive I",
 "Tyrannis Glaive II",
 "Pulsar Rod I",
 "Pulsar Rod II",
 "Pulsar Rod III",
 "Kadachi Pillar I",
 "Kadachi Pillar II",
 "Kadachi Pillar III",
 "Garon Rod I",
 "Garon Rod II",
 "Temptations Trident",
 "Vice",
 "Dragonbone Glaive I",
 "Dragonbone Glaive II",
 "Dragonbone Glaive III",
 "Indigo Flash",
 "Azure Bolt",
 "Verdant Levin",
 "Blacksteel Glaive I",
 "Blacksteel Glaive II",
 "Daoras Entom",
 "Daoras Tethidine ",
 "Xeno Shmaena",
 "Bad Wing",
 "Grunge Storm"
];

	type["BOW"] = [
 "Iron Bow I",
 "Iron Bow II",
 "Iron Bow III",
 "Steel Bow I",
 "Steel Bow II",
 "Steel Bow III",
 "Alloy Bow I",
 "Alloy Bow II",
 "Nergal Whisper",
 "Dooms Shaft",
 "Kulu Arrorw I",
 "Kulu Arrorw II",
 "Kulu Arrorw III",
 "Archers Dance I",
 "Archers Dance II",
 "Archers Dance III",
 "Brazencord",
 "Gigacles",
 "Princess Arrow I",
 "Princess Arrow II",
 "Rathslinger I",
 "Rathslinger II",
 "Rathslinger III",
 "Aqua Arrow I",
 "Aqua Arrow II",
 "Aqua Arrow III",
 "Water Shot I",
 "Water Shot II",
 "Water Shot III",
 "Glacial Arrow I",
 "Glacial Arrow II",
 "Snowfletcher",
 "Legia Snowfletcher",
 "Hunters Bow I",
 "Hunters Bow II",
 "Hunters Bow III",
 "Hunters Stoutbow I",
 "Hunters Stoutbow II",
 "Hunters Stoutbow III",
 "Hunters Proudbow I",
 "Hunters Proudbow II",
 "Hazak Velos I",
 "Hazak Velos II",
 "Diablos Bow I",
 "Diablos Bow II",
 "Diablos Bow III",
 "Diablos Coilbender I",
 "Diablos Coilbender II",
 "Galebender",
 "Cera Coilbender",
 "Blooming Arch I",
 "Blooming Arch II",
 "Blooming Arch III",
 "Datura String I",
 "Datura String II",
 "Datura String III",
 "Blazing Bow I",
 "Blazing Bow II",
 "Anja Arch I",
 "Anja Arch II",
 "Anja Arch III",
 "Pulsar Bow I",
 "Pulsar Bow II",
 "Pulsar Bow III",
 "Kadachi Strikebow",
 "Flying Kadachi Strikebow",
 "Dragonbone Bow I",
 "Dragonbone Bow II",
 "Dragonbone Bow III",
 "Blacksteel Bow I",
 "Blacksteel Bow II",
 "Icesteel Bow",
 "Daoras Sagittarii",
 "Xeno Metora",
 "Cross Hunters Bow",
 "Great Hunters Bow",
 "Insurgents Bow",
 "Villainous Brace",
 "Aloys Bow",
 "Aloys War Bow"
];
	
	type["LBG"] = [
 "Chain Blitz I",
 "Chain Blitz II",
 "Chain Blitz III",
 "High Chain Blitz I",
 "High Chain Blitz II",
 "High Chain Blitz III",
 "Cross Blitz I",
 "Cross Blitz II",
 "Nergal Spitter",
 "Cataclysms Trigger",
 "Lumu Blitz I",
 "Lumu Blitz II",
 "Lumu Typhon I",
 "Lumu Typhon II",
 "Lumu Typhon III",
 "Bazel Typhoon I",
 "Bazel Typhoon II",
 "Jagras Blitz I",
 "Jagras Blitz II",
 "Jagras Blitz III",
 "Jagras Fire I",
 "Jagras Fire II",
 "Jagras Fire III",
 "Flame Blitz I",
 "Flame Blitz II",
 "Rathbuster I",
 "Rathbuster II",
 "Thunder Blitz I",
 "Thunder Blitz II",
 "Lightning Blitz I",
 "Lightning Blitz II",
 "Lightning Blitz III",
 "Snow Blitz I",
 "Snow Blitz II",
 "Frost Blitz I",
 "Frost Blitz II",
 "Hunters Rifle I",
 "Hunters Rifle II",
 "Hunters Rifle III",
 "Power Rifle I",
 "Power Rifle II",
 "Power Rifle III",
 "Sniper Shot I",
 "Sniper Shot II",
 "Hazak Ereipia",
 "Gulgoleths Wail",
 "Blazing Rifle I",
 "Blazing Rifle II",
 "Anja Buster I",
 "Anja Buster II",
 "Anja Buster III",
 "Madness Rifle I",
 "Madness Rifle II",
 "Madness Rifle III",
 "Jyura Bullet I",
 "Jyura Bullet II",
 "Lava Bullet I",
 "Lava Bullet II",
 "Carapace Rifle I",
 "Carapace Rifle II",
 "Carapace Rifle III",
 "Barroth Shot I",
 "Barroth Shot II",
 "Barroth Shot III",
 "Garon Rifle I",
 "Garon Rifle II",
 "Fates Ember",
 "Karma",
 "Dragonbone Bowgun I",
 "Dragonbone Bowgun II",
 "Dragonbone Bowgun III",
 "Onigashima",
 "Dai-Onigashima",
 "Mythical Horn",
 "Mythical Horn+",
 "Mythical Three-Horn",
 "Blacksteel Crossbow I",
 "Blacksteel Crossbow II",
 "Icesteel Wasp",
 "Daoras Hornet",
 "Xeno Neqiina",
 "Cross Bowgun",
 "Great Bowgun",
 "Devils Grin",
 "Devils Madness"
];

	type["HBG"] = [
 "Iron Assault I",
 "Iron Assault II",
 "Iron Assault III",
 "Steel Assault I",
 "Steel Assault II",
 "Steel Assault III",
 "Chrome Assault I",
 "Chrome Assault II",
 "Nergal Roar",
 "Destructions Fusillade",
 "Aqua Assault I",
 "Aqua Assault II",
 "Aqua Assault III",
 "Water Cannon I",
 "Water Cannon II",
 "Water Cannon III",
 "Luminous Assault I",
 "Luminous Assault II",
 "Arma Destroyer I",
 "Arma Destroyer II",
 "Arma Destroyer III",
 "Shattercryst",
 "Shattercryst+",
 "Legia Shattercryst",
 "Jagras Assault I",
 "Jagras Assault II",
 "Jagras Assault III",
 "Jagras Cannon I",
 "Jagras Cannon II",
 "Gluttonous Fancannon",
 "Blazing Assault I",
 "Blazing Assault II",
 "Flammenkanone",
 "Gnashing Flammenkanone",
 "Bone Shooter I",
 "Bone Shooter II",
 "Bone Shooter III",
 "Heavy Shooter I",
 "Heavy Shooter II",
 "Heavy Shooter III",
 "Power Shooter I",
 "Power Shooter II",
 "Diablos Shooter I",
 "Diablos Shooter II",
 "Dual Threat",
 "Neros Blazooka",
 "Griffon Blazooka",
 "Blooming Shooter I",
 "Blooming Shooter II",
 "Blooming Shooter III",
 "Datura Blaster I",
 "Datura Blaster II",
 "Datura Blaster III",
 "Spiked Shooter I",
 "Spiked Shooter II",
 "Baan Roar I",
 "Baan Roar II",
 "Baan Roar III",
 "Gama Cannon I",
 "Gama Cannon II",
 "Pulsar Shooter I",
 "Pulsar Shooter II",
 "Pulsar Shooter III",
 "Kadachi Lion I",
 "Kadachi Lion II",
 "Kadachi Lion III",
 "Dragonbone Cannon I",
 "Dragonbone Cannon II",
 "Dragonbone Cannon III",
 "Quickcaster",
 "Quickcaster+",
 "Quickquiver",
 "Magda Gemitus I",
 "Magda Gemitus II",
 "Blacksteel Cannon I",
 "Blacksteel Cannon II",
 "Teostras Artillery",
 "Teostras Flames",
 "Xeno Jiiqa",
 "Gluttonous Cannon",
 "Dark Devourer"
];

	type["EVT"] = [

];



	function fillSelect(nValue,nList){

		nList.options.length = 1;
		var curr = type[nValue];
		for (each in curr)
			{
			 var nOption = document.createElement('option'); 
			 nOption.appendChild(document.createTextNode(curr[each])); 
			 nOption.setAttribute("value",curr[each]); 			 
			 nList.appendChild(nOption); 
			}
	}

</script>
<body>
	<form method="post" action="">
	   <fieldset>
			<select name='states' onchange="fillSelect(this.value,this.form['type'])">
				<option value="">Type</option>
				<option value="GSD">Great Sword</option>
				<option value="LSD">Long Sword</option>
				<option value="HAM">Hammer</option>
				<option value="HTH">Hunting Horn</option>
				<option value="DBL">Dual Blades</option>
				<option value="SAS">Sword and Sheild</option>
				<option value="LAN">Lance</option>
				<option value="GUL">Gun Lance</option>
				<option value="AWS">Switch Axe</option>
				<option value="CHB">Charge Blade</option>
				<option value="ING">Insect Glaive</option>
				<option value="BOW">Bow</option>
				<option value="LBG">Light Bowgun</option>
				<option value="HBG">Heavy Bowgun</option>
				<option value="EVT">Event Weapons</option>	

			</select>


			<select name='type'>
				<option value="">Select Weapon</option>
			</select>

	   </fieldset>

</body>
</html>